baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'ag'
theme = 'classic'

[markup.goldmark.renderer]
unsafe = true

[params]
description = "A Blog About Nothing"
custom_css = ["style.css"]
footer = """
[GitHub](https://github.com/alexgenco) |
<a rel="me" href="https://sfba.social/@genco">Mastodon</a> |
[Soundcloud](https://soundcloud.com/ricky-ricky-rice)
"""
