baseURL = 'https://alexgenco.github.io/'
languageCode = 'en-us'
title = 'ag'
theme = 'classic'

[markup.goldmark.renderer]
unsafe = true

[params]
custom_css = ["style.css"]
footer = "© 2022 Alex Genco"

[[menus.main]]
weight = 1
name = "tags"
url = "/tags/"

[[menus.feed]]
weight = 3
name = "gh"
url = "https://github.com/alexgenco"

[[menus.feed]]
weight = 2
name = "ig"
url = "https://www.instagram.com/alexgencoo/"

[[menus.feed]]
weight = 1
name = "m"
url = "https://sfba.social/@genco"
rel = "me"
