baseURL = 'https://alexgenco.github.io/'
languageCode = 'en-us'
title = 'ag'
theme = 'classic'

[markup.goldmark.renderer]
unsafe = true

[params]
description = "A Blog About Nothing"
custom_css = ["style.css"]
footer = "© 2022 Alex Genco"

[[menus.main]]
weight = 1
name = "about"
url = "/about/"

[[menus.main]]
weight = 2
name = "tags"
url = "/tags/"

[[menus.feed]]
weight = 3
name = "github"
url = "https://github.com/alexgenco"

[[menus.feed]]
weight = 2
name = "sourcehut"
url = "https://sr.ht/~alexgenco"

[[menus.feed]]
weight = 1
name = "mastodon"
url = "https://sfba.social/@genco"
rel = "me"
